### ISSUE TITLE
Fix deprecation warning in usage of failure crate

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#104]
The new `iter_causes` method does the `skip(1)` dance for us and now `causes` is deprecated too.

```
warning: use of deprecated item 'failure::Fail::causes': please use the 'iter_causes()' method instead
  --> twiggy/./twiggy.rs:22:20
   |
22 |         for c in e.causes().skip(1) {
   |                    ^^^^^^
   |
   = note: #[warn(deprecated)] on by default
```

**Comment by userzimmermann** [comment]
Hi @fitzgen :) Anybody working on this already? If not then please assign to me! It feels like the perfect start into the Rust WebAssembly world :8
