### ISSUE TITLE
Add AppVeyor CI for Windows

### ISSUE THREAD

**Issue by userzimmermann** [rustwasm/twiggy#117]
Hi! As a Windows user I was pretty confused about all those twiggy tests failing locally on my laptop... Until I figured it out that it's only about different line endings in expected output. I fixed that for now in #116 but think it would be generally good to also continuously run the build and tests on Windows via [AppVeyor](https://www.appveyor.com) integration. I have experience with AppVeyor and would volunteer to care about that :)

**Comment by fitzgen** [comment]
I have very little experience with AppVeyor, so if you could get all the scripts and metadata set up, then I could do the admin/config flip switching. Thanks for volunteering!

**Comment by AlexEne** [comment]
I'm closing this in favor of: https://github.com/rustwasm/twiggy/issues/580 that would also solve the windows case.
