### ISSUE TITLE
Add arguments to `monos` command

### ISSUE THREAD

**Issue by data-pup** [rustwasm/twiggy#125]
Building off of some discussion in #120:

> It might be nice to add a way to name specific generic functions that we would like to display, so that we could narrow down our test expectations a little.

**Comment by userzimmermann** [comment]
@data-pup: I'll take care of that :) I'm in such a twiggy flag run... I just can't stop anymore ;P

**Comment by data-pup** [comment]
Awesome! Thanks for helping out @userzimmermann :smile_cat: I know the feeling :P
