### ISSUE TITLE
Add ability to display specific subtree of dominators tree

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#15]
`$ svelte dominators $FUNCTION` should display just the given function's subtree in the dominator tree.

**Comment by fitzgen** [comment]
@data-pup go for it!

**Comment by data-pup** [comment]
This was solved in #51. Closing this now :)

**Comment by fitzgen** [comment]
FYI, if you put "fixes #1234" in a commit message or PR description, it will automatically close the issue when merged :)

**Comment by data-pup** [comment]
Ahh thanks! I had been tagging them, but it's good to know that there is a specific syntax for that :+1:
