### ISSUE TITLE
How Can I Build this applicaiton

### ISSUE THREAD

**Issue by Praveer1981** [rustwasm/twiggy#166]
Hi,
Is there any way to build it and get the twiggy.exe ?

**Comment by fitzgen** [comment]
If you are just trying to use it, see https://github.com/rustwasm/twiggy#-install

If you want to build and develop locally, see https://github.com/rustwasm/twiggy/blob/master/CONTRIBUTING.md#building-and-testing Afterwards the binary will be somewhere like `target/{debug,release}/twiggy[.exe]`.
