### ISSUE TITLE
It fails to output when I use .wasm file of 3+ MB 

### ISSUE THREAD

**Issue by Praveer1981** [rustwasm/twiggy#168]
Hi,
It seems to me that this tool is not capable of producing the output when the .wasm file size is bigger(even 5 MB ). However, it works well when I use a small size .wasm file.
Do you have any plan to fix this issue and release a new version of twiggy.exe.

**Comment by data-pup** [comment]
Hello! Thanks for filing an issue! That sounds troublesome, would love to look into this more. Do you happen to have any examples of the error you see when this happens? If possible, a link to a wasm binary that causes this might also be useful.

**Comment by fitzgen** [comment]
Hi @Praveer1981, as @data-pup mentions we need more information to understand the bug so we can fix it.

Help us help you and provide us with:

* The input `.wasm` file that Twiggy is failing on
* The exact command you are running, for example: `twiggy top input.wasm`
* Any console output, error messages and stack traces produced.
* The version of Twiggy you are running (or is it `master` from git?)

Thanks.

**Comment by AlexEne** [comment]
I'm closing this for now as I've successfully tested the latest release on a big file.
If the issue still persists, please re-open it with the `.wasm` repro file.
