### ISSUE TITLE
Add ability to summarize items by crate/namespace

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#17]
Maybe named

```
$ svelte summarize
```

?

Bonus points if we selectively summarize some items within certain crates/namespaces, but leave others un-summarized. For example, collapse all of `std` into one row in a result table, but have all the items in `my_crate` un-summarized.

**Comment by AlexEne** [comment]
If it's ok i'll close this in favor of https://github.com/rustwasm/twiggy/issues/581
