### ISSUE TITLE
Dominators with depth 1 seemingly doesn't demangle names

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/twiggy#174]
Using `twiggy-opt 0.3.0` on a wasm file as `twiggy dominators -d 1 foo.wasm` (trying to get all the roots of large sizes) prints out a lot of entries as `func [xx]`. I found this somewhat confusing because the wasm binary had the function names subsection, but it turns out that I needed to path `-d 2` because it looks like in the dominator tree there's a function node which dominates the node with the function's name. Using `twiggy dominators -d 2` did indeed print out the function names.

Would it be possible to have the function names come up at depth 1 as well?

**Comment by fitzgen** [comment]
I think the real fix is to get info from the name section for both the `Code[n]` element and the `Func[n]` element.

**Comment by data-pup** [comment]
I'll start looking into this now :cat:

**Comment by data-pup** [comment]
Taking another swing at this now, it's looking good so far :slightly_smiling_face:
