### ISSUE TITLE
Twiggy dominators row limiting seems to be ignored

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/twiggy#176]
Using [this wasm file](https://gist.github.com/alexcrichton/1c73f54d63bcab63fe9c6bc279d90c3d#file-pulldown_cmark_wasm_bg-wasm) executing `twiggy dominators -r 1` still seems to print all the rows! The `--help` page though indicates that `-r` is the maximum number of rows to display

**Comment by data-pup** [comment]
I believe that this will be fixed when #244 lands! :smiley_cat:

**Comment by data-pup** [comment]
Fixed :)
