### ISSUE TITLE
Incorrect indexing into functions

### ISSUE THREAD

**Issue by pepyakin** [rustwasm/twiggy#24]
Function exports refer functions via global function index. And global index space consist of all imported items concatenated with all defined items in the module.

Here is the code that uses global index to index into function section.
https://github.com/fitzgen/svelte/blob/5e1bcd3404583c05d8427e6900b967a52ec098e9/parser/wasm.rs#L400-L404

This code is incorrect because it uses to a global index to index into function section (which only contains defined functions).

**Comment by sendilkumarn** [comment]
@pepyakin I think it is #16 

That is what I have tried in #22 to determine global indices on the fly [here](https://github.com/sendilkumarn/svelte/blob/81982b8db50bd0cf961e259e7372cc6bd00e1683/parser/wasm.rs#L399-L433)
