### ISSUE TITLE
Confusing error with wasm "a.out"

### ISSUE THREAD

**Issue by sunfishcode** [rustwasm/twiggy#291]
## 🐛 Bug Description

Using the [wasi-sdk](https://github.com/CraneStation/wasi-sdk) to compile a C hello world testcase to a wasm binary and examine it with twiggy:
```
$ clang hello.c
$ file a.out 
a.out: WebAssembly (wasm) binary module version 0x1 (MVP)
$ twiggy top a.out 
error: Gimli error: UnexpectedEof
  caused by: UnexpectedEof
```
It wasn't immediately clear what was causing this problem. After some experimenting, it appears that twiggy is determining the file type from its name. "a.out" is clang's default for executables, including wasm "executables".
```
$ mv a.out hello.wasm
$ twiggy top hello.wasm 
 Shallow Bytes │ Shallow % │ Item
───────────────┼───────────┼──────────────────────────────────────────
          9699 ┊    25.80% ┊ printf_core
          6143 ┊    16.34% ┊ dlmalloc
          2364 ┊     6.29% ┊ data[0]
...
```
Similar things happen with .o files, though the symptoms are slightly different:
```
$ clang -c hello.c
$ file hello.o
hello.o: WebAssembly (wasm) binary module version 0x1 (MVP)
$ twiggy top hello.o
 Shallow Bytes │ Shallow % │ Item
───────────────┼───────────┼──────────────────
             0 ┊     0.00% ┊ Σ [0 Total Rows]
$ mv hello.o hello.o.wasm
$ twiggy top hello.o.wasm 
 Shallow Bytes │ Shallow % │ Item
───────────────┼───────────┼──────────────────────────────────────
            86 ┊    22.93% ┊ code[0]
            67 ┊    17.87% ┊ custom section 'linking'
            34 ┊     9.07% ┊ import env::__indirect_function_table
...
```

twiggy version: twiggy-opt 0.4.0

#### 🌍 Test Case

Take any wasm module file and rename it to "a.out" or "hello.o".

#### 👟 Steps to Reproduce

Take any wasm module file, rename it to "a.out" or "hello.o", and run `twiggy top` on it.

#### 😲 Actual Behavior

From the behavior and error messages, it appears twiggy is attempting to decode the wasm modules with a native object file decoder, and producing confusing output.

#### 🤔 Expected Behavior

If it's a deliberate choice to use the filename to determine which decoder to use, a more descriptive error message would help. Otherwise, wasm has a [magic cookie](https://stackoverflow.com/questions/43503981/how-to-check-the-webassembly-version-of-a-wasm-binary) which can be used.

**Comment by fitzgen** [comment]
We actually fixed this on master: https://github.com/rustwasm/twiggy/pull/260 and https://github.com/rustwasm/twiggy/issues/226

Just need to cut a release, which I will do now.
