### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#3]
`svelte` needs a team of people who can review each other's pull requests, and make consensus-based decisions together about its future.

Anyone who has made two meaningful contributions to `svelte` should seriously consider joining the team!

Drop a comment here if you are interested in joining.

**Comment by sendilkumarn** [comment]
I am in 🙂

**Comment by AlexEne** [comment]
Was `svelte` the previous name? I got confused on this vs the javascript lib. 
I'll close this for now as there probably will be some consideration needed once https://github.com/rustwasm/team/issues/294 resolves.

**Comment by lovingcg** [comment]
Can this tool display the source cpp file name?
