### ISSUE TITLE
Fetch all remote branches

### ISSUE THREAD

**Issue by roblevy** [rustwasm/twiggy#367]
## 💡 Feature Description

I want to pull a remote branch which I've never had in my local repo. I can fetch per-branch but to fetch every remote branch I need to do `Gfetch --all`. Given that there's a list of remote branches on Twiggy, I thought there might be a way to fetch _all_ the remote branches. I notice that `F` isn't mapped yet in Twiggy.

#### 💻 Example Usage

A user has been working on `branch1` and has already pushed to the remote:

```
r:origin
  HEAD
  branch1
```

A colleague has pushed `branch2` to the remote but this doesn't show up yet in Twiggy. The user presses `F` and the remote branch list updates (just like doing `Gfetch --all` does):

```
r:origin
  HEAD
  branch1
  branch2
```

#### 🙌 Are you interested in implementing this feature?

Add an "X" to one of the following:

* [ ] Yes
* [X] Yes if I had a mentor to help me
* [ ] No

I haven't ever dug into Vim development, so it feels like a big box to open...

**Comment by bjorn3** [comment]
I think you meant to open this issue at https://github.com/sodapopcan/vim-twiggy. This is the repo for a code size profiler, not a vim plugin.

**Comment by fitzgen** [comment]
Yeah, I think this is the wrong repo :)
