### ISSUE TITLE
Fix Nightly CI

### ISSUE THREAD

**Issue by data-pup** [rustwasm/twiggy#405]
## 🐛 Bug Description

It seems that the nightly build for CI is failing now. Not _quite_ sure what's causing this yet, but it looks like [this](https://travis-ci.com/rustwasm/twiggy/jobs/270375267):

```
0.00sadding /home/travis/.cargo to cache
creating directory /home/travis/.cargo
adding /home/travis/build/rustwasm/twiggy/target to cache
creating directory /home/travis/build/rustwasm/twiggy/target
adding /home/travis/.rustup to cache
creating directory /home/travis/.rustup
adding /home/travis/.cache/sccache to cache
creating directory /home/travis/.cache/sccache

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

Note: Also entirely plausible these errors are just something happening upstream, I'm not _quite_ confident about that though. :grey_question: :confused: :grey_question:

**Comment by bjorn3** [comment]
This is probably a cache which has grown too big. Every time a different rust version is used, cargo keeps the old artifacts in the target dir.

**Comment by data-pup** [comment]
Cache was part of the issue, thank you @bjorn3 for identifying that! I'll wait to close this until I've shepherded in some PR's that are currently open, but CI seems to be working again, via #408.
