### ISSUE TITLE
Add a `twiggy garbage` subcommand to find unreachable items

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#48]
This would print code and data that is not transitively referenced by any exports / public functions. Since linkers and compilers tend to remove dead code, this is more likely to find bugs in our IR graph, but that is also a useful thing ;)

**Comment by data-pup** [comment]
This looks like it would be fun! I would love to try and tackle this one. I can start looking into it tomorrow I believe. Let me know if you have any advice :)

**Comment by fitzgen** [comment]
@data-pup great! I would suggest using [`petgraph::visit::Dfs`](https://docs.rs/petgraph/0.4.12/petgraph/visit/struct.Dfs.html) traversal starting from the [meta-root](https://github.com/rustwasm/twiggy/blob/ece63ac9d02cd1e12c131b8bbb07be4c2a8094ba/ir/ir.rs#L186-L190) to collect the set of all items that are not garbage (ie transitively reachable from some exported or public item). Then, I would iterate over all items, filtering them down to just the items that *aren't* in the reachable set (ie are garbage), and then sort those garbage items by size. Does that all make sense?

**Comment by fitzgen** [comment]
This would mostly be implemented in `analyze/analyze.rs`. Although there is a bit of plumbing to add in most of the crates.

https://github.com/rustwasm/twiggy/commit/aa3330d9981d6568550c86a55c50795fc954380c is a good example of what implementing a new sub command is like.

**Comment by data-pup** [comment]
Awesome! That makes sense to me 🙂
