### ISSUE TITLE
Do something reasonable with indirect calls

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#5]
Maybe just root all the functions that could possible be called indirectly.

**Comment by bnjbvr** [comment]
(Just a random thought as I happen to read through these issues: if a function table is exported, all the functions must be implicitly rooted, since the JS table api contains setters.)

**Comment by fitzgen** [comment]
> (Just a random thought as I happen to read through these issues: if a function table is exported, all the functions must be implicitly rooted, since the JS table api contains setters.)

I'm not sure I follow -- You mean that the JavaScript APIs for working with a wasm module allow you to mutate the function tables?

**Comment by bnjbvr** [comment]
Oops, I confused myself. That will teach me to write something in a hassle :slightly_smiling_face: 
Only functions that are set in elements of function tables should be rooted, which is what you said in the initial comment. Sorry about the noise.
