### ISSUE TITLE
Each output format should be gated behind a cargo feature

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#56]
The twiggy binary should enable them all by default. The wasm API should enable only the JSON output format.

**Comment by fitzgen** [comment]
@csmoe maybe this is something you might be interested in picking up, since you're now intimately familiar with how different formats are emitted :)

**Comment by csmoe** [comment]
ok, I'll take care of this.

**Comment by csmoe** [comment]
@fitzgen do you mean this: `cargo twiggy --features json|csv|...`
