### ISSUE TITLE
Unknown opcode (at offset 76146)

### ISSUE THREAD

**Issue by Alexufo** [rustwasm/twiggy#577]
twiggy version: twiggy-opt 0.6.0
windows

>twiggy top "C:\test\engine_wasm.wasm"

`
error: WASM error: Unknown opcode (at offset 76146)
  caused by: Unknown opcode (at offset 76146)
`

What could it be?

**Comment by AlexEne** [comment]
Hi,

Could you try reproducing it on the latest version (building twiggy from latest `main` branch). This should have fixed it: 
https://github.com/rustwasm/twiggy/pull/576

Thanks
