### ISSUE TITLE
`twiggy paths` should work with regexes

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/twiggy#58]
It can be annoying to specify the whole item name, including the hash at the end. We should support doing just `my_crate::.*` etc.

**Comment by data-pup** [comment]
I can start working on this one when I am done working on #57!

**Comment by data-pup** [comment]
Now that #63 landed, I can start looking into this issue. Any advice on getting the regexes working is welcome, I figure the process here will end up looking very similar to whatever we need to do to get #59 fixed too.

**Comment by fitzgen** [comment]
The [regex crate](https://crates.io/crates/regex) is a joy to work with :)

**Comment by data-pup** [comment]
Solved in #65.
