### ISSUE TITLE
Add compatibility with ELF binaries

### ISSUE THREAD

**Issue by data-pup** [rustwasm/twiggy#69]
Tracking issue for adding ELF compatibility to twiggy.

#4 lists some binary formats that we would like to add compatibility for, including ELF, Mach-O, and PE/COFF. These might be somewhat involved tasks, so this issue will specifically track work/discussion related to adding ELF compatibility.

As mentioned in that issue, we can use [goblin](https://crates.io/crates/goblin) to parse IR nodes.

[gimli](https://crates.io/crates/gimli) is a library for consuming the DWARF debugging format, which may come in handy. [This](http://dwarfstd.org/doc/Debugging%20using%20DWARF-2012.pdf) is a good introduction link to DWARF. 

The [object](https://crates.io/crates/object) crate might also be useful for this, it is a "unified interface for parsing object file formats."

**Comment by fitzgen** [comment]
Thanks for digging into this :)

* I think we can largely handle both Mach-O and ELF at the same time by using `object`. They both use DWARF, and `object` allows us to just ask for the DWARF info without caring whether the thing is ELF or Mach-O.

* Just to start, I would suggest only constructing the call graph, essentially. Using `DW_AT_call_site` and the info about inlined routines (IIRC `DW_AT_inlined_subroutine` or something).

  This is all in the `.debug_info` section, aka `gimli::DebugInfo`. You can iterate over compilation units within `.debug_info` with https://docs.rs/gimli/0.15.0/gimli/struct.DebugInfo.html#method.units. To iterate over the entries in a unit, you need to parse the abbreviations with https://docs.rs/gimli/0.15.0/gimli/struct.CompilationUnitHeader.html#method.abbreviations and then pass the abbreviations through to the enties method https://docs.rs/gimli/0.15.0/gimli/struct.CompilationUnitHeader.html#method.entries

* I suspect we might need to change the representation of `twiggy_ir::Id`. Right now, it is somewhat specific to what works well with wasm.

* In general, following the same overall structure of the wasm parsing is a good bet. Implement the `Parse` trait and have two passes: the first to create IR items and the second to create edges between items.
