### ISSUE TITLE
[Feature Request]: Support Mach-O Binaries

### ISSUE THREAD

**Issue by alexisart** [rustwasm/twiggy#712]
## 💡 Feature Description

Allows profiling the size of Mach-O binaries as well as fat binaries for OSX

#### 💻 Example Usage

Currently, this just outputs:

```
 Shallow Bytes │ Shallow % │ Item
───────────────┼───────────┼──────────────────
             0 ┊     0.00% ┊ Σ [0 Total Rows]
```

or it complains about unknown file magic on the fat binaries.

The user would be able to run `$HOME/.cargo/bin/twiggy top -n 20 "/Users/runner/work/mygame/mygame/target/aarch64-apple-darwin/release/mygame" and then get the correct top 20 code size offenders.

#### 🙌 Are you interested in implementing this feature?

Add an "X" to one of the following:

* [ ] Yes
* [ ] Yes if I had a mentor to help me
* [x] No

**Comment by AlexEne** [comment]
Hi,

Twiggy just works on wasm/wasm32-wasi targets. I think you're looking for something like bloaty: https://github.com/google/bloaty
That should work on regular binaries.

**Comment by philipc** [comment]
It should work for Mach-O already if you point it at the dsym file instead of the executable.
